spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.1.8:1433;databaseName=decola
    username: decola
    password: 'decola'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        proc:
          param_null_passing: true
        enable_lazy_load_no_trans: true          
server:
  port: 8080
  servlet:
    contextPath: /